datasets:
  TargetedAttack:
    random_seed: 0
    initial_design_numdata: 10
    n_iter: 100
    render_kwargs:
      fps: 1
      mode: live
    fn_cls: NoisyFunction
    fn_params:
      obj_fn: 'lambda x:(6*x[0]-2)**2*np.sin(12*x[0]-4)'
      bnds: [[-1,1]]
      noise_mean: 0.0
      noise_var: 0.0001
    bo_model_params:
      prefit_param:
        sampler_cls: Grid
        prefit_n: 100
        fixed_kern: True
      kernel_cls: Matern52
      kernel_param:
        ARD: False
      model_params:
        noise_var: 0.005
        ARD: False
      bo_params:
        attack_init: True
        normalize_Y: False
        acquisition_type: LCB
        acquisition_weight_fn: 'lambda t: 0.5 * np.log(2*t)'
        plot_params:
          is_cache: False
    region_cls: CubeRegion
    region_param:
      coordinate: [0]
      length: 1.
      reward_fn: 'lambda x: 1. / (np.linalg.norm(coordinate - x) + 1.)'
algorithms:
  AggressiveSubtractionAttack:
    random_seed: 0
    delta: 10
    strategy_cls: SimpleStrategy
    strategy_kwargs:
      factor: 0.1
      consecutive_successes: 3
    #delta: 34.55205898257652
  # ClippingAttack:
  #   random_seed: 0
  #   f_x_tilda: -15.908745487888613
  #   delta: 5
  #   strategy_cls: SimpleStrategy
  #   strategy_kwargs:
  #     burnin_n: 10
  #     factor: 0.1
  #     consecutive_successes: 3
